# Explore

In [44]:
import json
from pathlib import Path
import dotenv
import polars as pl
from datetime import datetime
import time

dotenv.load_dotenv()

True

In [7]:
WETH_ADDRESS = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2".lower()
UNI_ADDRESS = "0x1f9840a85d5af5bf1d1762f925bdaddc4201f984".lower()
UNI_WETH_ADDRESS = "0x1f9840a85d5af5bf1d1762f925bdaddc4201f984".lower()

In [33]:
swaps_df = pl.read_parquet(Path("data/swaps.parquet"))
swaps_df.head()

shape: (5, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ block_tim ┆ transacti ┆ pool_addr ┆ addr0     ┆ … ┆ amount_we ┆ amount_to ┆ price_in_ ┆ log_pric │
│ estamp    ┆ on_hash   ┆ ---       ┆ ---       ┆   ┆ th        ┆ ken       ┆ weth      ┆ e_in_wet │
│ ---       ┆ ---       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ h        │
│ datetime[ ┆ str       ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---      │
│ μs, UTC]  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2025-07-0 ┆ 0x14877d3 ┆ 0x755f017 ┆ 0x6441922 ┆ … ┆ 0.021978  ┆ -6239.964 ┆ 286407.33 ┆ 12.56517 │
│ 1         ┆ 2c556a9cf ┆ 36f93c915 ┆ 91cc835a9 ┆   ┆           ┆ 303       ┆ 4631      ┆          │
│ 00:00:11  ┆ 477d0bb3f ┆ 85b840c21 ┆ 3d6330b24 ┆   ┆           ┆           ┆           ┆          │
│ UTC       ┆ 1fa…      ┆ 79c…      ┆ ea5…      ┆   ┆           ┆           ┆           ┆          │
│ 2025-07-0 ┆ 0x6ec27d2 ┆ 0x44f9469 ┆ 0x419c4db ┆ … ┆ 0.023879  ┆ -1313.204 ┆ 55533.799 ┆ 10.92474 │
│ 1         ┆ 416e404d1 ┆ d0d5393d3 ┆ 4b9e25d6d ┆   ┆           ┆ 847       ┆ 27        ┆ 7        │
│ 00:00:11  ┆ 7d5bb11c5 ┆ a01a0d4fa ┆ b2ad9691c ┆   ┆           ┆           ┆           ┆          │
│ UTC       ┆ ab5…      ┆ 14f…      ┆ cb8…      ┆   ┆           ┆           ┆           ┆          │
│ 2025-07-0 ┆ 0xa87e985 ┆ 0xe0554a4 ┆ 0xa0b8699 ┆ … ┆ -1.004674 ┆ 2499.0168 ┆ 2487.3602 ┆ 7.818977 │
│ 1         ┆ b5188a773 ┆ 76a092703 ┆ 1c6218b36 ┆   ┆           ┆ 34        ┆ 82        ┆          │
│ 00:00:11  ┆ 0ccdc0bdd ┆ abdb3ef35 ┆ c1d19d4a2 ┆   ┆           ┆           ┆           ┆          │
│ UTC       ┆ 3e6…      ┆ c80…      ┆ e9e…      ┆   ┆           ┆           ┆           ┆          │
│ 2025-07-0 ┆ 0xd483399 ┆ 0xe0554a4 ┆ 0xa0b8699 ┆ … ┆ 0.002004  ┆ -4.984539 ┆ 2487.3594 ┆ 7.818977 │
│ 1         ┆ 3e6769a24 ┆ 76a092703 ┆ 1c6218b36 ┆   ┆           ┆           ┆ 11        ┆          │
│ 00:00:11  ┆ 3330602ae ┆ abdb3ef35 ┆ c1d19d4a2 ┆   ┆           ┆           ┆           ┆          │
│ UTC       ┆ 8f2…      ┆ c80…      ┆ e9e…      ┆   ┆           ┆           ┆           ┆          │
│ 2025-07-0 ┆ 0xae57aa9 ┆ 0x3150b45 ┆ 0x643c4e1 ┆ … ┆ 0.0049875 ┆ -22.82654 ┆ 4590.4939 ┆ 8.431743 │
│ 1         ┆ f8e025c45 ┆ 0f8325ac4 ┆ 5d7d62ad0 ┆   ┆           ┆ 7         ┆ 99        ┆          │
│ 00:00:11  ┆ 745a22336 ┆ afbfa52f3 ┆ abec4a9bd ┆   ┆           ┆           ┆           ┆          │
│ UTC       ┆ 13a…      ┆ 3ec…      ┆ 4b0…      ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [46]:
df = swaps_df.filter(pl.col("addr0") == UNI_ADDRESS)
df.shape

(25193, 9)

In [45]:
with Path("data/weth_pools_by_address.json").open() as f:
    pools = json.load(f)

In [89]:
df["price_in_weth"][0:10]

shape: (10,)
Series: 'price_in_weth' [f64]
[
	348.32901
	348.378117
	348.377598
	348.377503
	348.427787
	348.468941
	348.674887
	348.737028
	348.740165
	348.964869
]

In [ ]:
[pools[pool_addr]["tokens"][1]["symbol"] for pool_addr in df["pool_addr"]]

In [84]:
[bt.timestamp() for bt in df["block_timestamp"][0:10]]

[1751328155.0,
 1751328635.0,
 1751328647.0,
 1751328887.0,
 1751329535.0,
 1751329799.0,
 1751329823.0,
 1751329835.0,
 1751329847.0,
 1751329967.0]